// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./web/routes/_404.tsx";
import * as $_app from "./web/routes/_app.tsx";
import * as $api_joke from "./web/routes/api/joke.ts";
import * as $greet_name_ from "./web/routes/greet/[name].tsx";
import * as $index from "./web/routes/index.tsx";
import * as $solar_system from "./web/routes/solar-system.tsx";
import * as $Counter from "./web/islands/Counter.tsx";
import * as $GraphicsViewer from "./web/islands/GraphicsViewer.tsx";
import * as $RustWasmGraphics from "./web/islands/RustWasmGraphics.tsx";
import * as $SimpleGraphics from "./web/islands/SimpleGraphics.tsx";
import * as $SimpleWasm from "./web/islands/SimpleWasm.tsx";
import * as $SolarSystem from "./web/islands/SolarSystem.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./web/routes/_404.tsx": $_404,
    "./web/routes/_app.tsx": $_app,
    "./web/routes/api/joke.ts": $api_joke,
    "./web/routes/greet/[name].tsx": $greet_name_,
    "./web/routes/index.tsx": $index,
    "./web/routes/solar-system.tsx": $solar_system,
  },
  islands: {
    "./web/islands/Counter.tsx": $Counter,
    "./web/islands/GraphicsViewer.tsx": $GraphicsViewer,
    "./web/islands/RustWasmGraphics.tsx": $RustWasmGraphics,
    "./web/islands/SimpleGraphics.tsx": $SimpleGraphics,
    "./web/islands/SimpleWasm.tsx": $SimpleWasm,
    "./web/islands/SolarSystem.tsx": $SolarSystem,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
